# Generated by Django 2.2.8 on 2019-12-07 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Полное имя')),
                ('avatar', models.ImageField(upload_to='')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='номер')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание поля')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('gender', models.CharField(choices=[['male', 'Крытай'], ['female', 'Не крытый']], default='male', max_length=10, verbose_name='Полe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
