# Generated by Django 2.2.8 on 2019-12-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
