# Generated by Django 2.2.8 on 2019-12-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0006_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
