# Generated by Django 2.2.8 on 2019-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0008_auto_20191208_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
        migrations.AddField(
            model_name='post',
            name='pole',
            field=models.CharField(choices=[['m', 'Крытай'], ['f', 'Не крытый']], default='m', max_length=10, verbose_name='Полe'),
        ),
    ]
