# Generated by Django 2.2.8 on 2019-12-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0009_auto_20191208_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
