# Generated by Django 2.2.8 on 2019-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0010_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar1',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='avatar2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
